:sparkles: Added a framework to represent and handle SiDB defects (#103)
* feat: Added data structures to represent fabrication defects on the H-Si(100) surface

* Distinction between charged and uncharged defects

* Spacing values and RST documentation

* docs: Fixed doxygenenum directive (does not support the 'members' operation)

* Added a function to compute the extent of single SiDB defects in a layout

* Added a function to compute all SiDBs on a surface that are affected by any defect

* feat: Added a simple parser to read printed Python arrays of integers as SiDB surface defects

* fix: Variable assignment fix under Windows

* fix: Underflow in for loop with negative values

* fix: Changed data types for loop variables

* fix: Windows underflow issue while comparing signed and unsigned integers

* feat: Added a blacklisting mechanism for exact to disable certain gate types on certain tiles

* fix: 'reference to local binding declared in enclosing function' compilation error that would occur on compilers other than GCC

* feat: Added an interface to extract functional information from gate libraries as well as a function that utilizes this information and maps it against an SiDB surface to blacklist tiles

* docs: Added RST documentation for truth table utils, SiDB surface analysis, and the new get_functional_implementations interface of gate libraries

* :sparkles: Added SiDB defect support to the SQD writer

* Changed the defects layer specification with respect to Samuel's input

* :label: Added an sidb_defect type that encapsulates the sidb_defect_type plus values for electrical charge, electric permittivity, and Thomas-Fermi screening distance

* :green_heart: Switched to single-threaded build for Coverage CI to consume less memory. This should fix out-of-memory errors and consequently failed compilations

* :green_heart: Fixed Window's "unexpected token 'attribute specifier'" error

* :heavy_plus_sign: Added tinyXML2 as a submodule

* :sparkles: Added an SQD file reader to parse SiDB layouts

* :white_check_mark: Added an SQD file reader tests to check for parsing errors

* :white_check_mark: Added more SQD file reader tests to check for valid dimer coordinates and dot indices

* :art: Simplified bounding box implementation

* :sparkles: Adjusted write_sqd_layout and read_sqd_layout to process SiDB defect types if implemented by the layout

* :white_check_mark: Updated a test case for the SQD reader to validate the proper parsing of coulomb values

* :white_check_mark: Added a test file for the SQD writer that incorporates the SQD reader

* :memo: Reflect SQD reader/writer changes in documentation

* :art: Adjust sqd file writer with respect to Samuel's feedback: leave out <coulomb> tag for uncharged defects

* :white_check_mark: Fix failing test in read_sqd_layout.cpp

* :building_construction: Added the possibility to blacklist gates based on their input/output ports, i.e., rotation

* :test_tube: Added a failing test for exact's functionality to respect the blacklisting based on rotations. This feature is not yet implemented

* :sparkles: Added the ability to exact to blacklist gates based on their port information

* :white_check_mark: Added EQ tests for blacklisted exact and functional tests for port_direction_to_coordinate

* :sparkles: Enabled sidb_surface_analysis to determine port orientations of blacklisted gates. Thereby, gates can be partially excluded from P&R only in certain orientations.

* :memo: Added documentation for the new optional fcn_gate_library interface.

* :memo: Just fixed a c&p error [skip ci]

* :memo: Added more documentation on the Bestagon gate library

* :green_heart: Removed a static_assert that was too strict

* :bug: Prevent writing defect layer headers if the given cell layout type does not implement the defect interface

* :building_construction: Allow exact to specify x- and y-dimensions for upper bounds separately

* :bug: Fixed layer order which is apparently very important for SiQAD

* :bug: Unknown defects are neutral

* :white_check_mark: Added a test case for the SiDB surface analysis

* :sparkles: Added the possibility to ignore specified defect types on the SiDB surface

* :sparkles: Added in-place overloads for read_sqd_layout

* Updated the Bestagon library with three tiles that are more stable against defects (AND, XOR, XNOR)

* :sparkles: Support for step edges and residual gunk surface defects

* :art: More generic test case for defect extend

* :recycle: Cleaned up code

* 💚 Fixed MSVC's `C1001: internal compiler error`  (#62)

* :green_heart: Trying to fix a "fatal  error C1001: Internal compiler error" in MSVC 2022

* :green_heart: Another attempt at fixing the internal compiler error on MSVC

* Updated tinyxml2

* :green_heart: Finally fixed (?) the MSVC compiler error

* :memo: Added documentation on the bug and its fix

* :memo: Fixed Read the Docs compilation

* :bug: Fixed merge artifacts

* :art: clang-tidy fixes

* :green_heart: Replace operators `and`, `or`, `not` with `&&`, `||`, `!` in `exact` additions to please MSVC

* :art: Applied clang-tidy

* Incorporated remaining resilient Bestagon gates

* Added resilient Bestagon gates as SQD resources

* :rotating_light: Applied clang-tidy

* :white_check_mark: Fix sidb_surface_analysis tests which were failing due to the updated Bestagon library

* :rotating_light: Fix compiler warning

* :alembic: Changed charged defect exclusion spacing to 10nm in accordance with simulation results

* :alembic: Defect-aware physical design experiment

* :alembic: Python script to create defective surfaces

* :bug: added "const" for return iterator of find function (#80)

Co-authored-by: Drewniok <jan.drewniok.reseaqrch@gmail.com>
Co-authored-by: Marcel Walter <marcel.walter@tum.de>

* :art: Adjusted code based on advancements in main

* new constructor for sidb_surface.cpp added (#84)

* :sparkles: new constructor for sidb_surface to generate a surface from an aspect_ratio

Co-authored-by: Drewniok <jan.drewniok.reseaqrch@gmail.com>
Co-authored-by: Marcel Walter <marcel.walter@tum.de>

* :green_heart: Workaround for MSVC being petty

* :green_heart: Prevent experiment from being built if Z3 is disabled

* :green_heart: Workaround for MSVC being petty

* :art: Consistency fix

* :art: Split the upper_bound parameter into an x and y coordinate for consistency with exact

* :fire: Removed design files

* :bug: Fixed `tinyxml2` header positioning

* :truck: Renamed script to better express its purpose

* :memo: Added missing documentation for input parsing functions

* :art: Fixed missing includes

* :art: ClangFormat changes

Signed-off-by: ClangFormat <ClangFormat@users.noreply.github.com>

* :memo: Added missing documentation on file writers

* :art: Fixed missing phmap in clang-format

* :art: Moved from std::set to std::unordered_set

* :memo: Fixed documentation

* :art: Addressed clang-tidy's comments

* :art: Addressed further clang-tidy comments

* :green_heart: Fixed a build issue

* :alembic: Updated experiment script

* :alembic: Provide fall-back experiment implementations in case Z3 is not available

---------

Signed-off-by: ClangFormat <ClangFormat@users.noreply.github.com>
Co-authored-by: Jan Drewniok <97012901+Drewniok@users.noreply.github.com>
Co-authored-by: Drewniok <jan.drewniok.reseaqrch@gmail.com>
Co-authored-by: ClangFormat <ClangFormat@users.noreply.github.com>